# Generated by Django 5.1.2 on 2024-11-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0005_alter_submission_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
